### ISSUE TITLE
doesn't work anymore; Cannot read property 'style' of null

### ISSUE THREAD

**Issue by subtleGradient** [saschanaz/AtomScroller#2]
```
C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:241 Failed to activate package named 'atom-scroller' TypeError: Cannot read property 'style' of null
    at Object.patchEditor (C:\Users\Thomas\.atom\packages\atom-scroller\lib\atom-scroller.js:28:16)
    at C:\Users\Thomas\.atom\packages\atom-scroller\lib\atom-scroller.js:78:29
    at WorkspaceView.module.exports.WorkspaceView.eachEditorView (C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\workspace-view.js:92:9)
    at Object.exports.activate (C:\Users\Thomas\.atom\packages\atom-scroller\lib\atom-scroller.js:77:56)
    at Package.module.exports.Package.activateNow (C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:235:27)
    at C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:221:28
    at Package.module.exports.Package.measure (C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:215:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package-manager.js:464:21)
    at C:\Users\Thomas\AppData\Local\atom\app-0.182.0\resources\app\src\package-manager.js:445:29
```

**Comment by daMupfel** [comment]
Same Problem here
